-- migrations/004_mosques.sql
-- WhereWePraying Stage 2: Mosque Directory (Find a Mosque feature)
-- Generated: 2026-09-03T22:27:22.891288

-- Mosques table: core directory data
CREATE TABLE IF NOT EXISTS mosques (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  address TEXT,
  postcode TEXT,
  latitude REAL,
  longitude REAL,
  website_url TEXT,
  active INTEGER DEFAULT 1,
  type TEXT DEFAULT 'mosque',
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mosques_city ON mosques(city);
CREATE INDEX IF NOT EXISTS idx_mosques_active ON mosques(active);

-- Jama'ah times table: daily prayer congregation times
CREATE TABLE IF NOT EXISTS thm_jamaah_times (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mosque TEXT NOT NULL,
  date TEXT NOT NULL,
  fajr_jamaah TEXT,
  zuhr_jamaah TEXT,
  asr_jamaah TEXT,
  maghrib_jamaah TEXT,
  isha_jamaah TEXT,
  source TEXT,
  updated_at TEXT NOT NULL,
  UNIQUE(mosque, date),
  FOREIGN KEY(mosque) REFERENCES mosques(slug)
);

CREATE INDEX IF NOT EXISTS idx_thm_jamaah_mosque ON thm_jamaah_times(mosque);
CREATE INDEX IF NOT EXISTS idx_thm_jamaah_date ON thm_jamaah_times(date);

-- Mosque photos table (for future use)
CREATE TABLE IF NOT EXISTS mosque_photos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mosque TEXT NOT NULL,
  r2_key TEXT,
  status TEXT DEFAULT 'pending',
  uploaded_at TEXT NOT NULL,
  FOREIGN KEY(mosque) REFERENCES mosques(slug)
);

CREATE INDEX IF NOT EXISTS idx_mosque_photos_mosque ON mosque_photos(mosque);

-- Insert London mosques

INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('ilford-islamic-centre', 'Ilford Islamic Centre', 'London', '52-56 Albert Road, Ilford', 'IG1 1HW', 51.556536, 0.075737, 'ilfordmosque.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('redbridge-islamic-centre-ric-gants-hill-mosque', 'Redbridge Islamic Centre (RIC) / Gants Hill Mosque', 'London', '28-28A, 34 and 36 Woodford Avenue, Gants Hill, Ilford', 'IG2 6XG', 51.57786, 0.06552, 'redbridgeislamiccentre.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('ilford-muslim-community-centre-and-mosque', 'Ilford Muslim Community Centre and Mosque', 'London', 'Community Centre, Eton Road, Ilford', 'IG1 2UE', 51.550059, 0.079522, 'ilfordmuslimsociety.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('seven-kings-masjid', 'Seven Kings Masjid', 'London', '645-647 High Road, Seven Kings', 'IG3 8RA', 51.564485, 0.098057, 'skmet.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('chadwell-heath-muslim-centre', 'Chadwell Heath Muslim Centre', 'London', '1041-1043 High Road, Chadwell Heath', 'RM6 4AU', 51.569579, 0.124324, 'chadwellheathmuslimcentre.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-kalaam-academy', 'Al Kalaam Academy', 'London', '566 Cranbrook Road, Ilford', 'IG2 6RE', 51.579324, 0.073222, 'alkalaam.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('newbury-park-mosque', 'Newbury Park Mosque', 'London', '117 Oaks Lane, Newbury Park, Ilford', 'IG2 7PY', 51.581688, 0.093552, 'newburyparkmasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('redbridge-muslim-community-centre', 'Redbridge Muslim Community Centre', 'London', '712 Eastern Avenue, Newbury Park, Ilford', 'IG2 6PE', 51.573408, 0.082824, 'redbridgemcc.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-al-ansar', 'Masjid Al Ansar', 'London', '833-835 High Road, Goodmayes', 'IG3 8TD', 51.566525, 0.108684, 'masjidansar.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-dawatul-islam-balfour-road', 'Masjid Dawatul Islam (Balfour Road)', 'London', '112 Balfour Road, Ilford', 'IG1 area', NULL, NULL, 'ilfordmuslimsociety.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('havering-islamic-cultural-centre-hicc', 'Havering Islamic Cultural Centre (HICC)', 'London', '91 Waterloo Road, Romford', 'RM7 0AA', 51.572442, 0.180091, 'haveringmosque.org.uk (also haveringislamiccentre.org.uk per Charity Commission)', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('romford-mosque', 'Romford Mosque', 'London', '29 Lessington Avenue, Romford', 'RM7 9EB', 51.573072, 0.165978, 'romfordmosque.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('rainham-muslim-community-mosque', 'Rainham Muslim Community Mosque', 'London', 'Royals Youth Centre, Viking Way, Rainham', 'RM13 9YG', 51.519066, 0.19076, 'rainhammuslimcommunity.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('collier-row-masjid', 'Collier Row Masjid', 'London', '148A Chase Cross Road, Romford', 'RM5 3UU', 51.601221, 0.172761, 'collierrowmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-ummah-hornchurch', 'Darul Ummah Hornchurch', 'London', '10 Maybank Avenue, Hornchurch', 'RM12 5SA', 51.545512, 0.203928, 'duhornchurch.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-madina-mosque-barking-barking-muslims-association', 'Al Madina Mosque Barking (Barking Muslims Association)', 'London', '2 Victoria Road, Barking', 'IG11 8PY', 51.543911, 0.07578, 'barkingmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('essex-islamic-academy-ripple-road-mosque', 'Essex Islamic Academy (Ripple Road Mosque)', 'London', '343 Ripple Road, Barking', 'IG11 7RJ/RR', NULL, NULL, 'essexislamicacademy.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('dagenham-ummah-welfare-trust', 'Dagenham Ummah Welfare Trust', 'London', '5 Hewett Road, Dagenham', 'RM8 2XT', NULL, NULL, 'duwt.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('madina-foundation-dagenham-east', 'Madina Foundation Dagenham East', 'London', '539 Rainham Road South, Dagenham', 'RM10 7XJ', 51.546473, 0.164426, 'madinafoundationdagenham.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-ihsaan-barking', 'Darul Ihsaan Barking', 'London', '86 Longbridge Road, Barking', 'IG11 8SF', 51.541343, 0.084563, 'darulihsaanbarking.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('dagenham-jamme-masjid-diwa', 'Dagenham Jamme Masjid (DIWA)', 'London', 'Barnmead Road, Dagenham (Fanshawe Community Complex)', 'RM9 5DX', 51.546893, 0.144875, 'dagenhamjammemasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-ummah-goresbrook', 'Darul Ummah Goresbrook', 'London', '36 Maplestead Road, Dagenham', 'RM9 4XR', NULL, NULL, 'darulummahgoresbrook.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('thames-view-muslim-association', 'Thames View Muslim Association', 'London', 'Thames View Community Hall, Bastable Ave, Barking (also seen: 17 Farr Ave)', 'IG11 0LG / 0NY', NULL, NULL, 'tvmacharity.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('jabir-bin-zayd-islamic-centre-markaz-imam-jabir-bin-zayd', 'Jabir bin Zayd Islamic Centre (Markaz Imam Jabir Bin Zayd)', 'London', 'Medite House, Broadway, Barking', 'IG11 7LS', 51.535936, 0.07722, 'ahlulistiqamah.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('riverside-muslim-association-rivergate-centre-the-wilds', 'Riverside Muslim Association (Rivergate Centre + The Wilds)', 'London', 'Rivergate Centre, Minter Rd, Barking / Northgate Road, Barking', 'IG11 0FJ / 0AN', NULL, NULL, 'riversidemuslimassociation.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-hikma', 'Darul Hikma', 'London', '949 Green Lane, Dagenham', 'RM8 1DJ', 51.561448, 0.140797, 'darulhikma.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('noor-ul-huda-masjid-noor-ul-huda', 'Noor Ul Huda (Masjid Noor Ul Huda)', 'London', 'Unit 4, 4 Creek Road, Barking', 'IG11 0JH', 51.523994, 0.099425, 'jamianoorulhuda.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hatfield-community-hall-rented-venue', 'Hatfield Community Hall (rented venue)', 'London', '71 Hatfield Road, Dagenham', 'RM9 6JS', 51.538808, 0.13753, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('barking-community-forum-rented-venue', 'Barking Community Forum (rented venue)', 'London', '28 Stephen Jewers Gardens, Barking', 'IG11 9FA', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('lsc-community-hub-rented-venue', 'LSC Community Hub (rented venue)', 'London', 'Martin Peters Court, Meadow Road, Upney', 'IG11 9FE', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('village-community-hall-rented-venue', 'Village Community Hall (rented venue)', 'London', '64 Vicarage Road, Romford', 'RM10 9SD', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('green-lane-community-centre-glcc-rented-venue', 'Green Lane Community Centre - GLCC (rented venue)', 'London', '691 1st floor Green Lane, Dagenham', 'RM8 1UU', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('heath-park-community-centre-rented-venue', 'Heath Park Community Centre (rented venue)', 'London', 'Rusholme Ave, Dagenham', 'RM10 7PR', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('mayesbrook-park-jumu-ah-service-rented-venue', 'Mayesbrook Park Jumu''ah Service (rented venue)', 'London', 'Barking Sporthouse & Gym, Mayesbrook Park, Lodge Avenue, Dagenham', 'RM8 2JR', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('longbridge-community-centre-rented-venue', 'Longbridge Community Centre (rented venue)', 'London', '153B-155 Becontree Ave, Dagenham', 'RM8 2UL', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('ripple-centre-rented-venue', 'Ripple Centre (rented venue)', 'London', 'Ripple Road, Barking', 'IG11 7PB', NULL, NULL, 'barkingdagenhamjamah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('beckton-islamic-association', 'Beckton Islamic Association', 'London', '18 Warwall, London Beckton', 'E6 6WG', NULL, NULL, 'becktonislamicassociation.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-arqam', 'Darul Arqam', 'London', '17 Jutland Road, Canning Town', 'E13 8JH', NULL, NULL, 'darularqam.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-al-humera', 'Masjid Al-Humera', 'London', '113 Romford Road', 'E15 4LY', NULL, NULL, 'masjidal-humera.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('cann-hall-deen-education-trust', 'Cann Hall Deen & Education Trust', 'London', '145 Cann Hall Rd, Leytonstone', 'E11 3NJ', NULL, NULL, 'cannhall.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('chingford-mosque', 'Chingford Mosque', 'London', '92 Chingford Mount Road', 'E4 9AA', NULL, NULL, 'chingfordmosque.com (also chingfordmasjid.com)', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-uloom-qadria-jilania', 'Darul Uloom Qadria Jilania', 'London', '12 East Ave, Walthamstow', 'E17 9NG', NULL, NULL, 'dqj.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('faizan-e-islam', 'Faizan E Islam', 'London', '757 Lea Bridge Rd, Walthamstow (+ second site: 8 Corbett Rd)', 'E17 9DZ / E17 3JZ', NULL, NULL, 'faizaneislam.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('leytonstone-masjid', 'Leytonstone Masjid', 'London', 'Dacre Rd, Leyton (Leytonstone Islamic Association)', 'E11 3AG', NULL, NULL, 'leytonstonemasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-madrassah-al-tawhid-trust', 'Masjid & Madrassah al-Tawhid Trust', 'London', '80 High Road, Leyton', 'E15 2BP', NULL, NULL, 'masjidtawhid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-abu-bakr', 'Masjid Abu Bakr', 'London', '26a Mansfield Rd, Walthamstow', 'E17 6PJ', NULL, NULL, 'masjidabubakr.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-e-umer', 'Masjid E Umer', 'London', '79 Queens Road, Walthamstow', 'E17 8QR', NULL, NULL, 'masjideumer.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('muslim-community-trust-mctleyton', 'Muslim Community Trust (MCTLeyton)', 'London', '324-328 High Rd, Leyton', 'E10 5PW', NULL, NULL, 'mctleyton.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('noor-ul-islam', 'Noor Ul Islam', 'London', '713 High Road, Leyton', 'E10 5AB', NULL, NULL, 'noorulislam.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('waltham-forest-islamic-association-wfia', 'Waltham Forest Islamic Association (WFIA)', 'London', '439-451 Lea Bridge Rd, Leyton', 'E10 7EA', NULL, NULL, 'wfia.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('aziziye-masjid', 'Aziziye Masjid', 'London', '117 Stoke Newington Road', 'N16 8BU', NULL, NULL, 'aziziye.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('madina-masjid-hackney', 'Madina Masjid (Hackney)', 'London', '2a Lea Bridge Road', 'E5 9QD', NULL, NULL, 'madina-masjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-quba-hackney', 'Masjid Quba (Hackney)', 'London', '70-72 Cazenove Road', 'N16 6AA', NULL, NULL, 'masjidequba.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-at-tarbiyah', 'Masjid at-Tarbiyah', 'London', '49-51 Leswin Road', 'N16 7NX', NULL, NULL, 'masjidtarbiyah.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-ramadan', 'Masjid Ramadan', 'London', '9-15 Shacklewell Lane', 'E8 2DA', NULL, NULL, 'masjidramadan.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('suleymaniye-masjid', 'Suleymaniye Masjid', 'London', '212-216 Kingsland Road', 'E2 8AX', NULL, NULL, 'suleymaniye.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('finsbury-park-mosque', 'Finsbury Park Mosque', 'London', '7-11 St Thomas''s Road, Finsbury Park', 'N4 2QH', NULL, NULL, 'finsburyparkmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-yusuf', 'Masjid Yusuf', 'London', '440 Hornsey Road, Holloway', 'N19 4EB', NULL, NULL, 'masjideyusuf.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('muslim-welfare-house', 'Muslim Welfare House', 'London', '233 Seven Sisters Road, Finsbury Park', 'N4 2DA', NULL, NULL, 'mwht.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-risalah-mosque', 'Al-Risalah Mosque', 'London', '91-93 Parkhurst Road', 'N7 0LP', NULL, NULL, 'alrisaalah.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-nehar-mosque', 'Al-Nehar Mosque', 'London', '70 Caledonian Road, King''s Cross', 'N1 9DN', NULL, NULL, 'alneharmosque.wordpress.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('king-s-cross-mosque', 'King''s Cross Mosque', 'London', 'Sandfield (Basement), Cromer Street', 'WC1H 8DU', NULL, NULL, 'kingscrossmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('jalalia-jamme-masjeed-jjme', 'Jalalia Jamme Masjeed (JJME)', 'London', '228 High Street, Ponders End', 'EN3 4EZ', NULL, NULL, 'jjme.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('palmers-green-mosque-mcec', 'Palmers Green Mosque (MCEC)', 'London', '30 Oakthorpe Road', 'N13 5JL', NULL, NULL, 'mcec.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('eic-al-masjid-trust-edmonton', 'EIC Al-Masjid Trust (Edmonton)', 'London', '20-34 Raynham Road, Edmonton', 'N18 2SJ', NULL, NULL, 'eicalmasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('rumi-mosque-mevlana-rumi-mosque', 'Rumi Mosque (Mevlana Rumi Mosque)', 'London', '337 Fore Street, Edmonton', 'N9 0NU', NULL, NULL, 'rumimosque.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('enfield-town-islamic-centre-mosque', 'Enfield Town Islamic Centre & Mosque', 'London', '5 Silver Street, Enfield', 'EN1 3EF', NULL, NULL, 'etic.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('ponders-end-islamic-centre', 'Ponders End Islamic Centre', 'London', '114-116 Nags Head Road, Ponders End', 'EN3 7AP', NULL, NULL, 'pondersendislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('satuq-bughra-khan-mosque-uyghur-education-centre', 'Satuq Bughra Khan Mosque & Uyghur Education Centre', 'London', '611A Green Lanes', 'N13 4EP', NULL, NULL, 'satuqbughrakhan.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('assunnah-islamic-centre', 'Assunnah Islamic Centre', 'London', '565A High Road, Tottenham', 'N17 6SB', NULL, NULL, 'assunnah.co.uk (also assunnah.moosdesign.co.uk)', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('london-islamic-cultural-centre', 'London Islamic Cultural Centre', 'London', '389-395 Wightman Road, Hornsey', 'N8 0NA', NULL, NULL, 'londonislamicculturalsociety.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-ayesha', 'Masjid Ayesha', 'London', '115 Clyde Road, Tottenham', 'N15 4JZ', NULL, NULL, 'masjidayesha.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('king-s-cross-mosque-camden-listing', 'King''s Cross Mosque (Camden listing)', 'London', 'Sandfield (Basement), Cromer Street', 'WC1H 8DU', NULL, NULL, 'kingscrossmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('kilburn-islamic-centre', 'Kilburn Islamic Centre', 'London', '292-294 Kilburn High Road', 'NW6 2DB', NULL, NULL, 'thekic.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('ianl-north-finchley', 'IANL (North Finchley)', 'London', '685 High Road, North Finchley', 'N12 0DA', NULL, NULL, 'ianl.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('high-barnet-islamic-centre', 'High Barnet Islamic Centre', 'London', '1 Bath Place, Hadley, Barnet', 'EN5 5XE', NULL, NULL, 'darulnoor.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('barnet-islamic-centre', 'Barnet Islamic Centre', 'London', '18 Brookhill Road', 'EN4 8SD', NULL, NULL, 'barnetislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hendon-mosque-islamic-centre', 'Hendon Mosque & Islamic Centre', 'London', 'Brent View Road', 'NW9 7EL', NULL, NULL, 'hendonmosque.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('edgware-central-mosque', 'Edgware Central Mosque', 'London', '48 High Street, Edgware', 'HA8 7EJ', NULL, NULL, 'edgwarecentralmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('islamic-centre-edgware', 'Islamic Centre Edgware', 'London', '9d Deansbrook Road, Edgware', 'HA8 9BE', NULL, NULL, 'islamiccentreedgware.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('madina-islamic-centre-cricklewood', 'Madina Islamic Centre (Cricklewood)', 'London', '356 Cricklewood Lane', 'NW2 2QL', NULL, NULL, 'madinaislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('islamic-centre-colindale', 'Islamic Centre Colindale', 'London', '223 Edgware Road', 'NW9 6LR', NULL, NULL, 'islamiccentrecolindale.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('greenwich-islamic-centre-gic-woolwich-mosque', 'Greenwich Islamic Centre (GIC) / Woolwich Mosque', 'London', '131 Plumstead Road, Plumstead', 'SE18 7DW', NULL, NULL, 'gicuk.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('greenwich-madina-trust-ghousia-masjid', 'Greenwich Madina Trust (Ghousia Masjid)', 'London', '56 Camrose Street, Thamesmead/Abbey Wood', 'SE2 0JA', NULL, NULL, 'greenwichmadinatrust.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('plumstead-islamic-centre', 'Plumstead Islamic Centre', 'London', '2 Plumstead Common Road, Plumstead', 'SE18 3AP', NULL, NULL, 'plumsteadislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('thamesmead-islamic-centre', 'Thamesmead Islamic Centre', 'London', 'Arch 16, 16 Byron Close, Thamesmead', 'SE28 8AA', NULL, NULL, 'thamesmeadislamiccentre.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('kidbrooke-islamic-centre', 'Kidbrooke Islamic Centre', 'London', 'Kidbrooke Community Hub (rented venue), Kidbrooke', 'SE3', NULL, NULL, 'kidbrookeislamiccentre.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('south-east-educational-culture-centre-seecc', 'South East Educational Culture Centre (SEECC)', 'London', 'St Mary''s Community Centre, 180 Eltham High Street (Jummah venue)', 'SE9 1BJ', NULL, NULL, 'selecc.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('mottingham-eltham-islamic-centre-meic', 'Mottingham & Eltham Islamic Centre (MEIC)', 'London', 'Anstridge Community Hall (Jummah venue) / 62 Mottingham Road (classes)', 'SE9 2LL', NULL, NULL, 'meislamic.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('lewisham-islamic-centre-lic', 'Lewisham Islamic Centre (LIC)', 'London', '363-365 Lewisham High Street', 'SE13 6NZ', NULL, NULL, 'lewishamislamiccentre.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('deptford-islamic-centre', 'Deptford Islamic Centre', 'London', '228-229 Railway Arches, Childers Street', 'SE8 5JR', NULL, NULL, 'deptfordislamiccentre.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('beca-masjid-new-cross', 'BECA Masjid (New Cross)', 'London', '170 New Cross Road', 'SE14 5AA', NULL, NULL, 'becamasjid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('sydenham-islamic-centre', 'Sydenham Islamic Centre', 'London', 'Temporary rented premises, Sydenham', 'SE26', NULL, NULL, 'sydenhamislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('nwkma-masjid-abu-bakar-crayford-mosque', 'NWKMA & Masjid Abu Bakar (Crayford Mosque)', 'London', '60 Crayford High Street, Crayford', 'DA1 4EF', NULL, NULL, 'nwkma.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('bexley-islamic-centre-masjid-omar-faruq', 'Bexley Islamic Centre (Masjid Omar Faruq)', 'London', 'Upper Wickham Lane, Welling', 'DA16 3AD', NULL, NULL, 'bexleyislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shahjalal-education-cultural-centre-sidcup-masjid', 'Shahjalal Education & Cultural Centre (Sidcup Masjid)', 'London', '5 Hatherley Road, Sidcup', 'DA14 4BH', NULL, NULL, 'seccsidcup.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('icmg-bexley', 'ICMG Bexley', 'London', 'Unit 19, Riverside Shopping Centre, 10-15 Town Square, Erith', 'DA8', NULL, NULL, 'icmgbexley.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('bromley-islamic-centre', 'Bromley Islamic Centre', 'London', '94 High Street (First Floor)', 'BR1 1EY', NULL, NULL, 'bromleyislamiccentre.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('penge-mosque-southeast-london-islamic-cultural-centre-slicc', 'Penge Mosque / Southeast London Islamic & Cultural Centre (SLICC)', 'London', 'Preston House, Clevedon Road, Penge (+ satellite at 4 Bromley Road, Beckenham)', 'SE20 7QE', NULL, NULL, 'pengemosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-emaan-centre-keston', 'Al-Emaan Centre (Keston)', 'London', 'Croydon Road, Keston', 'BR2 8HF', NULL, NULL, 'al-emaan.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('nurani-cultural-centre-mosque-green-street-green', 'Nurani Cultural Centre & Mosque (Green Street Green)', 'London', '105 High Street, Green Street Green, Orpington', 'BR6 6BJ', NULL, NULL, 'nuraniculturalcentre.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-uloom-london-school-mosque', 'Darul Uloom London (school mosque)', 'London', 'Foxbury Avenue, Chislehurst', 'BR7 6SD', NULL, NULL, 'darululoomlondon.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('croydon-mosque-islamic-centre-cmic', 'Croydon Mosque & Islamic Centre (CMIC)', 'London', '525 London Road, Thornton Heath', 'CR7 6AR', NULL, NULL, 'croydonmosque.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('croydon-islamic-community-trust-cict', 'Croydon Islamic Community Trust (CICT)', 'London', '89 London Road, West Croydon', 'CR0 2RF', NULL, NULL, 'croydonict.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-khair-foundation-musallah', 'Al Khair Foundation Musallah', 'London', '109-117 Cherry Orchard Road', 'CR0 6BE', NULL, NULL, 'alkhair.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('thornton-heath-islamic-centre', 'Thornton Heath Islamic Centre', 'London', '150 Gillett Road, Thornton Heath', 'CR7 8SN', NULL, NULL, 'thislamiccentre.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('purley-masjid-purley-islamic-community-centre', 'Purley Masjid (Purley Islamic Community Centre)', 'London', '130 Brighton Road / 63 Whytecliffe Road South, Purley', 'CR8 2AZ', NULL, NULL, 'purleymasjid.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('south-norwood-islamic-community-centre-masjid-uthman', 'South Norwood Islamic Community Centre (Masjid Uthman)', 'London', '3 Clifford Road, South Norwood', 'SE25 5JJ', NULL, NULL, 'snicc.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('norbury-muslim-centre', 'Norbury Muslim Centre', 'London', '1116 London Road, Norbury', 'SW16 4DT', NULL, NULL, 'norburymuslimcentre.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shirley-muslim-association-scca-southwing', 'Shirley Muslim Association (SCCA Southwing)', 'London', '28 Shrublands Avenue, Shirley', 'CR0 8JA', NULL, NULL, 'shirleyma.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('brixton-mosque-and-islamic-cultural-centre', 'Brixton Mosque and Islamic Cultural Centre', 'London', '1 Gresham Road, Brixton', 'SW9 7PH', NULL, NULL, 'brixtonmasjid.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('north-brixton-islamic-cultural-centre-nbicc', 'North Brixton Islamic Cultural Centre (NBICC)', 'London', '180-182A Brixton Road', 'SW9 6AT', NULL, NULL, 'nbicc.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('lambeth-masjid-progressive-community-centre', 'Lambeth Masjid & Progressive Community Centre', 'London', '194 Coldharbour Lane, Brixton', 'SE5 9QH', NULL, NULL, 'lambethmasjid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('emca-nagashi-mosque-centre', 'EMCA Nagashi Mosque & Centre', 'London', '283-291 Wandsworth Road, Stockwell', 'SW8 2ND', NULL, NULL, 'emca.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('west-norwood-mosque', 'West Norwood Mosque', 'London', '58-60 Norwood High Street, West Norwood', 'SE27 9NW', NULL, NULL, 'westnorwoodmosque.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('south-london-islamic-centre-streatham-mosque', 'South London Islamic Centre (Streatham Mosque)', 'London', '8 Mitcham Lane, Streatham', 'SW16 6NN', NULL, NULL, 'slicmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hyderi-islamic-centre-imam-baqir-a-s-centre', 'Hyderi Islamic Centre (Imam Baqir (a.s) Centre)', 'London', '26 Estreham Road, Streatham', 'SW16 5PQ', NULL, NULL, 'hyderi.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('new-peckham-mosque', 'New Peckham Mosque', 'London', '99-101 Cobourg Road, Peckham', 'SE5 0HU', NULL, NULL, 'newpeckhammosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('camberwell-islamic-centre', 'Camberwell Islamic Centre', 'London', '188 Camberwell Road', 'SE5 0ED', NULL, NULL, 'camberwellislamiccentre.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('bait-ul-aziz-islamic-cultural-centre', 'Bait-ul-Aziz Islamic Cultural Centre', 'London', '1 Dickens Square', 'SE1 4JL', NULL, NULL, 'baitulazizmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('beca-masjid-peckham-branch', 'BECA Masjid (Peckham branch)', 'London', '2nd Floor, Khan''s Bargains, Peckham High Street', 'SE15 4ST', NULL, NULL, 'becamasjid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('walworth-road-mosque-dairatul-amni', 'Walworth Road Mosque (Dairatul Amni)', 'London', '175A Walworth Road', 'SE17 1RW', NULL, NULL, 'dairatul-amni.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('balham-masjid-tooting-islamic-centre', 'Balham Masjid & Tooting Islamic Centre', 'London', '47 Balham High Road (+ 145 Upper Tooting Road)', 'SW12 9AW', NULL, NULL, 'balhammosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('islamic-culture-education-centre-battersea-mosque', 'Islamic Culture & Education Centre (Battersea Mosque)', 'London', '73-75 Falcon Road, Battersea', 'SW11 2PF', NULL, NULL, 'icecbattersea.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('the-london-mosque-fazl-mosque', 'The London Mosque (Fazl Mosque)', 'London', '16 Gressenhall Road, Southfields', 'SW18 5QL', NULL, NULL, 'ahmadiyyauk.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('sunni-muslim-association-south-london', 'Sunni Muslim Association (South London)', 'London', '20 Tooting Bec Road, Tooting', 'SW17 8BD', NULL, NULL, 'suma.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('idara-e-jaaferiya', 'Idara-e-Jaaferiya', 'London', '18 Church Lane, Tooting', 'SW17 9PP', NULL, NULL, 'idara-e-jaaferiya.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('dar-ul-amaan-islamic-centre', 'Dar Ul Amaan Islamic Centre', 'London', '54 Merton High Street, Colliers Wood', 'SW19 1DH', NULL, NULL, 'darulamaanmasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('morden-islamic-centre', 'Morden Islamic Centre', 'London', '116 London Road, Morden', 'SM4 5AY', NULL, NULL, 'miconline.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('wimbledon-mosque', 'Wimbledon Mosque', 'London', '262-264 Durnsford Road', 'SW19 8DS', NULL, NULL, 'wimbledonmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('baitul-futuh-mosque', 'Baitul Futuh Mosque', 'London', '181 London Road, Morden', 'SM4 5AE', NULL, NULL, 'baitulfutuh.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('sutton-central-masjid', 'Sutton Central Masjid', 'London', '25 Carshalton Road', 'SM1 4LF', NULL, NULL, 'suttoncentralmasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('sutton-islamic-centre-sic', 'Sutton Islamic Centre (SIC)', 'London', '62 Oakhill Road', 'SM1 3AG', NULL, NULL, 'suttonislamiccentre.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('muslim-cultural-welfare-association-of-sutton-mcwas', 'Muslim Cultural & Welfare Association of Sutton (MCWAS)', 'London', 'Wentworth Hall, 80 Ruskin Road, Carshalton', 'SM5 3DH', NULL, NULL, 'mcwas.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('kingston-jamia-mosque-kingston-muslim-association', 'Kingston Jamia Mosque (Kingston Muslim Association)', 'London', '55-57 East Road', 'KT2 6EJ', NULL, NULL, 'kingstonmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shiraz-mirza-trust-manor-park-hall', 'Shiraz Mirza Trust — Manor Park Hall', 'London', '316B Malden Road, New Malden', 'KT3 6AU', NULL, NULL, 'shirazm.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hounslow-jamia-masjid-islamic-centre', 'Hounslow Jamia Masjid & Islamic Centre', 'London', '367 Wellington Road South', 'TW4 5HU', NULL, NULL, 'hounslowmasjid.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-furqan-education-trust', 'Al Furqan Education Trust', 'London', '33-41 Cross Lances Road', 'TW3 2AD', NULL, NULL, 'alfurqaneducationtrust.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hayes-muslim-centre-islamic-education-cultural-society', 'Hayes Muslim Centre (Islamic Education & Cultural Society)', 'London', '3 Pump Lane, Hayes', 'UB3 3NB', NULL, NULL, 'hayesmuslimcentre.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-falah-centre', 'Al Falah Centre', 'London', 'The Forge, St Stephens Road', 'UB7 7RL', NULL, NULL, 'alfalahinstitute.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('wembley-central-masjid-wembley-central-mosque', 'Wembley Central Masjid (Wembley Central Mosque)', 'London', '35-37 Ealing Road, Wembley', 'HA0 4AE', NULL, NULL, 'wembleycentralmasjid.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('central-mosque-of-brent', 'Central Mosque of Brent', 'London', 'Marley Walk / 41 Station Parade, Willesden Green', 'NW2 4PU', NULL, NULL, 'centralmosqueofbrent.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('mosque-islamic-centre-of-brent-micb', 'Mosque & Islamic Centre of Brent (MICB)', 'London', '33a Howard Road / 26a Chichele Road, Cricklewood', 'NW2 6DS', NULL, NULL, 'micb.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('markaz-us-sunnah', 'Markaz Us-Sunnah', 'London', '500 Sunleigh Road, Alperton', 'HA0 4NF', NULL, NULL, 'musunnah.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('afghan-islamic-cultural-centre', 'Afghan Islamic Cultural Centre', 'London', '212-214 Church Road, Willesden', 'NW10 9NP', NULL, NULL, 'aiccmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('central-jamia-masjid-southall', 'Central Jamia Masjid (Southall)', 'London', '6 Montague Waye, Southall', 'UB2 5PA', NULL, NULL, 'cjmsouthall.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('bilal-masjid-greenford', 'Bilal Masjid Greenford', 'London', '82-90 Horsenden Lane North, Greenford', 'UB6 7QH', NULL, NULL, 'bilalmasjid.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('harrow-central-mosque-masood-islamic-centre', 'Harrow Central Mosque & Masood Islamic Centre', 'London', '34 Station Road', 'HA1 2SQ', NULL, NULL, 'harrowmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('sri-lankan-muslim-cultural-centre', 'Sri Lankan Muslim Cultural Centre', 'London', '2 Whitefriars Avenue, Wealdstone', 'HA3 5RN', NULL, NULL, 'slmcc.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-muntada-al-islami-trust', 'Al Muntada Al Islami Trust', 'London', '7 Bridges Place, Parsons Green', 'SW6 4HW', NULL, NULL, 'almuntadatrust.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('west-london-islamic-cultural-centre', 'West London Islamic Cultural Centre', 'London', '7 Bridges Place, Parsons Green', 'SW6 4HW', NULL, NULL, 'wlicc.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hammersmith-islamic-association', 'Hammersmith Islamic Association', 'London', '30-32 Bradmore Park Road', 'W6 0DT', NULL, NULL, 'hammersmithmasjid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('masjid-daar-us-sunnah', 'Masjid Daar us Sunnah', 'London', 'Market Approach, Lime Grove, Shepherds Bush Market', 'W12 8DE', NULL, NULL, 'Website listed by council directory; not independently re-confirmed', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('nadi-centre-royal-park', 'Nadi Centre Royal Park', 'London', '260 Old Oak Common Lane', 'NW10 6DX', NULL, NULL, 'mynadi.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shepherd-s-bush-mosque-muslim-cultural-centre', 'Shepherd''s Bush Mosque & Muslim Cultural Centre', 'London', '302 Uxbridge Road, Shepherds Bush', 'W12 7LJ', NULL, NULL, 'shepherdsbushmosque.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-manaar-muslim-cultural-heritage-centre-mchc', 'Al-Manaar Muslim Cultural Heritage Centre (MCHC)', 'London', '244 Acklam Road, North Kensington', 'W10 5YG', NULL, NULL, 'almanaar.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('london-central-mosque-regent-s-park-mosque-islamic-cultural-centre', 'London Central Mosque (Regent''s Park Mosque) & Islamic Cultural Centre', 'London', '146 Park Road, Marylebone', 'NW8 7RG', NULL, NULL, 'iccuk.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('westminster-bengali-welfare-trust-wbwt-prayer-venues', 'Westminster Bengali Welfare Trust (WBWT) prayer venues', 'London', '19 Sherbourne House + 5A Dryburgh House, Abbots Manor, Pimlico', 'SW1V 4LP / SW1V 4ET', NULL, NULL, 'wbwt.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('salahuddin-trust-masjid-salahuddin', 'Salahuddin Trust (Masjid Salahuddin)', 'London', '1 Norfolk Place, Tyburnia/Paddington', 'W2 1QN', NULL, NULL, 'salahuddintrust.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('mayfair-islamic-centre', 'Mayfair Islamic Centre', 'London', '19 Hertford Street, Mayfair', 'W1J 7RU', NULL, NULL, 'mayfairislamiccentre.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('egyptian-bureau-for-cultural-and-educational-affairs-jummah-only', 'Egyptian Bureau for Cultural and Educational Affairs (Jummah only)', 'London', '4 Chesterfield Gardens, Mayfair', 'W1J 5BG', NULL, NULL, 'new.egyculture.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('high-commission-for-pakistan-prayer-room', 'High Commission for Pakistan prayer room', 'London', '34-36 Lowndes Square, Knightsbridge', 'SW1X 9JN', NULL, NULL, 'phclondon.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-aqsa-masjid', 'Al Aqsa Masjid', 'London', '3 Thorne House, Launch Street', 'E14 3LU', NULL, NULL, 'alaqsadockland.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('al-huda-mosque', 'Al Huda Mosque', 'London', '91 Mile End Road', 'E1 4UN', NULL, NULL, 'alhudamosque.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('ashaadibi-mosque', 'Ashaadibi Mosque', 'London', '167 Cannon Street Road', 'E1 2LX', NULL, NULL, 'ashaadibi.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('baitul-aman-mosque', 'Baitul Aman Mosque', 'London', '101 Braintree Street', 'E2 0FT', NULL, NULL, 'baitulaman.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('bow-muslim-community-centre', 'Bow Muslim Community Centre', 'London', '509-517 Roman Road', 'E3 5EL', NULL, NULL, 'bowmosque.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('bow-muslim-cultural-centre-bow-central-mosque', 'Bow Muslim Cultural Centre (Bow Central Mosque)', 'London', '246 Bow Road', 'E3 3AP', NULL, NULL, 'bowcentralmosque.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('brick-lane-jamme-masjid', 'Brick Lane Jamme Masjid', 'London', '59 Brick Lane', 'E1 6QL', NULL, NULL, 'bricklanejammemasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('dar-al-arqam', 'Dar Al Arqam', 'London', '1 Michell House, Kitcat Terrace', 'E3 2SA', NULL, NULL, 'daralarqam.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('darul-ummah-jame-masjid', 'Darul Ummah Jame Masjid', 'London', '56 Bigland Street', 'E1 2ND', NULL, NULL, 'darulummah.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('east-london-mosque-trust', 'East London Mosque Trust', 'London', '82-92 Whitechapel Road', 'E1 1JQ', NULL, NULL, 'eastlondonmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('esha-a-tul-islam-ford-square-mosque', 'Esha''a tul Islam (Ford Square Mosque)', 'London', '16 Ford Square', 'E1 2HS', NULL, NULL, 'eshaatulislam.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('hifzul-quran-islamic-education-centre-masjid-al-fath', 'Hifzul Quran Islamic Education Centre (Masjid Al-Fath)', 'London', '304-306 Burdett Road, Pixley Street', 'E14 7DQ', NULL, NULL, 'hqiec.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('limehouse-masjid', 'Limehouse Masjid', 'London', '304-306 Stocks Place', 'E14 8AE', NULL, NULL, 'limehousemasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('madina-jamme-masjid', 'Madina Jamme Masjid', 'London', '248 Westferry Road', 'E14 3AG', NULL, NULL, 'madinamasjiddocklands.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('mazahirul-uloom-london', 'Mazahirul Uloom London', 'London', '241-243 Mile End Road', 'E1 4AA', NULL, NULL, 'mul.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('mimbar-academy', 'Mimbar Academy', 'London', '71 Smeed Road', 'E3 2NE', NULL, NULL, 'mimbar.co.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('poplar-shahjalal-mosque', 'Poplar Shahjalal Mosque', 'London', '25 Hale Street', 'E14 0BF', NULL, NULL, 'poplarshahjalal.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shadwell-gardens-tra', 'Shadwell Gardens TRA', 'London', '129 Shadwell Gardens, Cable Street', 'E1 2QL', NULL, NULL, 'shadwelltra.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shadwell-jame-masjid', 'Shadwell Jame Masjid', 'London', '143-145 Railway Arches, Shadwell Place', 'E1 2QB', NULL, NULL, 'shadwelljamemasjid.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shahporan-masjid-and-islamic-centre-trust', 'Shahporan Masjid and Islamic Centre Trust', 'London', '444 Hackney Road', 'E2 6QN', NULL, NULL, 'shahporanmasjid.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('shoreditch-masjid-islamic-cultural-centre', 'Shoreditch Masjid & Islamic Cultural Centre', 'London', '53-55 Redchurch Street', 'E2 7DJ', NULL, NULL, 'shoreditchmosque.com', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('stepney-shahjalal-mosque-cultural-centre', 'Stepney Shahjalal Mosque & Cultural Centre', 'London', '81-83 Duckett Street', 'E1 4TD', NULL, NULL, 'stepneyshahjalalmosque.org.uk', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('the-markazi-masjid-london', 'The Markazi Masjid London', 'London', '9-11 Christian Street', 'E1 1SE', NULL, NULL, 'markazimasjid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('turners-locksley-community-centre-turners-road-masjid', 'Turners & Locksley Community Centre (Turners Road Masjid)', 'London', '11 Bangla Close', 'E3 4YD', NULL, NULL, 'turnersroadmasjid.org', '2026-09-03T22:27:22.891324');
INSERT OR IGNORE INTO mosques (slug, name, city, address, postcode, latitude, longitude, website_url, created_at) VALUES ('weavers-fields-prayer-hall-trust', 'Weavers Fields Prayer Hall Trust', 'London', 'Railway Arch, 3A Brady Street', 'E1 5DT', NULL, NULL, 'weaversfield-muslim-prayer-hall.ueniweb.com', '2026-09-03T22:27:22.891324');